### ISSUE TITLE
Links all routes to `homepage`

### ISSUE THREAD

**Issue by mytnguyen26** [mytnguyen26/algo-shadow#20]
**Describe the bug**
On our homepage, we cannot get to `Algorithm`, `About` page by clicking on the links.

**To Reproduce**
1. run `npm run dev` to spin up server
2. Click on http://localhost:5173/
3. Click on Algorithm
4. Click on About

**Expected behavior**
When clicking on Algorithm links or About links, it should lead to route `/algorithm/` and `/about` 

**Screenshots**

![image](https://github.com/mytnguyen26/algo-shadow/assets/49925370/ecb497fb-3570-4d7b-b503-0100d0e7b9b4)

**Comment by Summer-luna** [comment]
all routes will works after authentication service branch merged into dev

**Comment by mytnguyen26** [comment]
implemented in #17
